### PR TITLE
Round trip 

### PR DESCRIPTION
**Pull request by UtkarshKr007**
Round trip Checkbox,Field and Icon are now added to AddRide and RideList

### CODE REVIEW

**Comment by michael-small** [comment]
Overall: Looks good, functions good. I would accept the request, but I have a few concerns:

1. Needs some unit tests and some e2e tests.
2. I am getting errors like "DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('time') does not support selection" or "DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection." when I add a ride. It adds but those go off. Never seen that before. Investigating that as I write this.
3. @nkfoss the commit ea27e7a removes the comment of "// Please keep this as the default value, or you will have problems with form validation / seats available as a rider." Should it be added back in? It seemed like an important reminder.

**Comment by UtkarshKr007** [comment]
My bad. I was rearranging things, I will grab that comment from another branch and add it back in. Regarding the DOMException, where does that happen? Console?

**Comment by michael-small** [comment]
Console, when the time or seats field is clicked into or when clicking out of the field.

**Comment by michael-small** [comment]
After doing some digging, I jumped into master and continued to get the issue. It's weird because I don't remember this being an issue at all last iteration, but it seems it is a project with the project from the start.

**Comment by michael-small** [comment]
I found the heart of the issue: https://github.com/angular/material2/issues/8516#issuecomment-345326000

Basically, it's a weird disconnect between Chrome's device mocking and IOS. This is only an issue when I select an IOS device mockup type to look at in the chrome dev console. Selecting any non-IOS device and then refreshing makes the error go away. From my understanding of the issue, I don't think this is a real problem we can/should address.

**Comment by UtkarshKr007** [comment]
Awesome

**Comment by nkfoss** [comment]
Looks good to me!

**Pull request merged**
